add __check_option()

diff --git a/build/packaging/linux/bin/kbnd b/build/packaging/linux/bin/kbnd
--- a/build/packaging/linux/bin/kbnd
+++ b/build/packaging/linux/bin/kbnd
@@ -107,20 +107,9 @@ status_auto_restart_daemon() {
 }
 
 #------------------------Related to Klaytn node functions-----------------------------
-start_node() {
-    __pid_run
-    [ -n "$pid" ] && echo "kbnd already running...[$pid]" && return
-
-    if [ ! -f $KEY_PATH ]; then
-        echo
-        echo "  [ERROR] : KEY_PATH is not defined in $CONF/kbnd.conf"
-        exit 1
-    fi
-
-    echo -n "Starting kbnd: "
-
+__check_option() {
     if [ ! -d $LOG_DIR ]; then
-        mkdir -p $LOG_DIR
+            mkdir -p $LOG_DIR
     fi
 
     if [ ! -d $DATA_DIR ]; then
@@ -129,6 +118,7 @@ start_node() {
 
     set -f
     OPTIONS="--nodekey ${KEY_PATH}"
+
     if [[ ! -z $NETWORK_ID ]] && [[ $NETWORK_ID != "" ]]; then
         OPTIONS="$OPTIONS --networkid $NETWORK_ID"
     fi
@@ -152,11 +142,29 @@ start_node() {
     if [ ! -z $DATA_DIR ]; then
         OPTIONS="$OPTIONS --datadir $DATA_DIR"
     fi
+    set +f
+}
 
+start_node() {
+    __pid_run
+    [ -n "$pid" ] && echo "kbnd already running...[$pid]" && return
+
+    if [ ! -f $KEY_PATH ]; then
+        echo
+        echo "  [ERROR] : KEY_PATH is not defined in $CONF/kbnd.conf"
+        exit 1
+    fi
+
+    echo -n "Starting kbnd: "
+
+    __check_option
+
+    set -f
     $BIN/kbn ${OPTIONS} >> ${LOG_DIR}/kbnd.out 2>&1 &
     RETVAL=$?
     PIDNUM=$!
     set +f
+
     if [ $RETVAL = 0 ]; then
         echo $PIDNUM > ${pidfile}
         echo "OK"
diff --git a/build/packaging/linux/bin/kcnd b/build/packaging/linux/bin/kcnd
--- a/build/packaging/linux/bin/kcnd
+++ b/build/packaging/linux/bin/kcnd
@@ -119,170 +119,175 @@ status_auto_restart_daemon() {
 }
 
 #------------------------Related to Klaytn node functions-----------------------------
+__check_option() {
+  if [ ! -d $LOG_DIR ]; then
+          mkdir -p $LOG_DIR
+      fi
+
+      set -f
+      OPTIONS=""
+
+      if [[ ! -z $METRICS ]] && [[ $METRICS -eq 1 ]]; then
+          OPTIONS="$OPTIONS --metrics"
+      fi
+
+      if [[ ! -z $PROMETHEUS ]] && [[ $PROMETHEUS -eq 1 ]]; then
+          OPTIONS="$OPTIONS --prometheus"
+      fi
+
+      if [[ ! -z $DB_NO_PARALLEL_WRITE ]] && [[ $DB_NO_PARALLEL_WRITE -eq 1 ]]; then
+          OPTIONS="$OPTIONS --db.no-parallel-write"
+      fi
+
+      if [[ ! -z $MULTICHANNEL ]] && [[ $MULTICHANNEL -eq 1 ]]; then
+          OPTIONS="$OPTIONS --multichannel"
+      fi
+
+      if [[ ! -z $RPC_ENABLE ]] && [[ $RPC_ENABLE -eq 1 ]]; then
+          OPTIONS="$OPTIONS --rpc"
+          if [ ! -z $RPC_API ]; then
+              OPTIONS="$OPTIONS --rpcapi $RPC_API"
+          fi
+          if [ ! -z $RPC_PORT ]; then
+              OPTIONS="$OPTIONS --rpcport $RPC_PORT"
+          fi
+          if [ ! -z $RPC_ADDR ]; then
+              OPTIONS="$OPTIONS --rpcaddr $RPC_ADDR"
+          fi
+          if [ ! -z $RPC_CORSDOMAIN ]; then
+              OPTIONS="$OPTIONS --rpccorsdomain $RPC_CORSDOMAIN"
+          fi
+          if [ ! -z $RPC_VHOSTS ]; then
+              OPTIONS="$OPTIONS --rpcvhosts $RPC_VHOSTS"
+          fi
+      fi
+
+      if [[ ! -z $WS_ENABLE ]] && [[ $WS_ENABLE -eq 1 ]]; then
+          OPTIONS="$OPTIONS --ws"
+          if [ ! -z $WS_API ]; then
+              OPTIONS="$OPTIONS --wsapi $WS_API"
+          fi
+          if [ ! -z $WS_PORT ]; then
+              OPTIONS="$OPTIONS --wsport $WS_PORT"
+          fi
+          if [ ! -z $WS_ADDR ]; then
+              OPTIONS="$OPTIONS --wsaddr $WS_ADDR"
+          fi
+          if [ ! -z $WS_ORIGINS ]; then
+              OPTIONS="$OPTIONS --wsorigins $WS_ORIGINS"
+          fi
+      fi
+
+      # Cypress network => NETWORK_ID is null && NETWORK = "cypress"
+      # Baobab network => NETWORK_ID is null && NETWORK = "baobab"
+      # Else => private network
+      if [[ -z $NETWORK_ID ]]; then
+          if [[ $NETWORK == "baobab" ]]; then
+              OPTIONS="$OPTIONS --baobab"
+          elif [[ $NETWORK == "cypress" ]]; then
+              OPTIONS="$OPTIONS --cypress"
+          else
+              echo
+              echo "[ERROR] network id is not specified and network is not available."
+              echo "Available network: baobab, cypress"
+              exit 1
+          fi
+      else
+          OPTIONS="$OPTIONS --networkid $NETWORK_ID"
+          echo "[INFO] creating a private network: $NETWORK_ID"
+          if [[ ! -z $NETWORK ]]; then
+              echo
+              echo "[WARN] ignoring the specified network: $NETWORK"
+          fi
+      fi
+
+      if [ ! -z $DATA_DIR ]; then
+          OPTIONS="$OPTIONS --datadir $DATA_DIR"
+      fi
+
+      if [ ! -z $PORT ]; then
+          OPTIONS="$OPTIONS --port $PORT"
+      fi
+
+      if [ ! -z $SUBPORT ]; then
+          OPTIONS="$OPTIONS --subport $SUBPORT"
+      fi
+
+      if [ ! -z $SERVER_TYPE ]; then
+          OPTIONS="$OPTIONS --srvtype $SERVER_TYPE"
+      fi
+
+      if [ ! -z $VERBOSITY ]; then
+          OPTIONS="$OPTIONS --verbosity $VERBOSITY"
+      fi
+
+      if [ ! -z $TXPOOL_EXEC_SLOTS_ALL ]; then
+          OPTIONS="$OPTIONS --txpool.exec-slots.all $TXPOOL_EXEC_SLOTS_ALL"
+      fi
+
+      if [ ! -z $TXPOOL_NONEXEC_SLOTS_ALL ]; then
+          OPTIONS="$OPTIONS --txpool.nonexec-slots.all $TXPOOL_NONEXEC_SLOTS_ALL"
+      fi
+
+      if [ ! -z $TXPOOL_EXEC_SLOTS_ACCOUNT ]; then
+          OPTIONS="$OPTIONS --txpool.exec-slots.account $TXPOOL_EXEC_SLOTS_ACCOUNT"
+      fi
+
+      if [ ! -z $TXPOOL_NONEXEC_SLOTS_ACCOUNT ]; then
+          OPTIONS="$OPTIONS --txpool.nonexec-slots.account $TXPOOL_NONEXEC_SLOTS_ACCOUNT"
+      fi
+
+      if [ ! -z $SYNCMODE ]; then
+          OPTIONS="$OPTIONS --syncmode $SYNCMODE"
+      fi
+
+      if [ ! -z $MAXCONNECTIONS ]; then
+          OPTIONS="$OPTIONS --maxconnections $MAXCONNECTIONS"
+      fi
+
+      if [ ! -z $LDBCACHESIZE ]; then
+          OPTIONS="$OPTIONS --db.leveldb.cache-size $LDBCACHESIZE"
+      fi
+
+      if [[ ! -z $NO_DISCOVER ]] && [[ $NO_DISCOVER -eq 1 ]]; then
+          OPTIONS="$OPTIONS --nodiscover"
+      fi
+
+      if [[ ! -z $BOOTNODES ]] && [[ $BOOTNODES != "" ]]; then
+          OPTIONS="$OPTIONS --bootnodes $BOOTNODES"
+      fi
+
+      if [[ ! -z $ADDITIONAL ]] && [[ $ADDITIONAL != "" ]]; then
+          OPTIONS="$OPTIONS $ADDITIONAL"
+      fi
+
+      if [[ ! -z $REWARDBASE ]] && [[ $REWARDBASE != "" ]]; then
+          OPTIONS="$OPTIONS --rewardbase $REWARDBASE"
+      fi
+
+      if [[ ! -z $AUTO_RESTART ]] && [[ $AUTO_RESTART -eq 1 ]]; then
+          OPTIONS="$OPTIONS --autorestart.enable"
+      fi
+
+      BASEDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
+      CURRENTFILE=`basename "$0"`
+      OPTIONS="$OPTIONS --autorestart.daemon.path $BASEDIR/$CURRENTFILE"
+
+      set +f
+}
+
 start_node() {
     __pid_run
     [ -n "$pid" ] && echo "kcnd already running...[$pid]" && return
 
     echo -n "Starting kcnd: "
 
-    if [ ! -d $LOG_DIR ]; then
-        mkdir -p $LOG_DIR
-    fi
-
     set -f
-    OPTIONS=""
-
-    if [[ ! -z $METRICS ]] && [[ $METRICS -eq 1 ]]; then
-        OPTIONS="$OPTIONS --metrics"
-    fi
-
-    if [[ ! -z $PROMETHEUS ]] && [[ $PROMETHEUS -eq 1 ]]; then
-        OPTIONS="$OPTIONS --prometheus"
-    fi
-
-    if [[ ! -z $DB_NO_PARALLEL_WRITE ]] && [[ $DB_NO_PARALLEL_WRITE -eq 1 ]]; then
-        OPTIONS="$OPTIONS --db.no-parallel-write"
-    fi
-
-    if [[ ! -z $MULTICHANNEL ]] && [[ $MULTICHANNEL -eq 1 ]]; then
-        OPTIONS="$OPTIONS --multichannel"
-    fi
-
-    if [[ ! -z $RPC_ENABLE ]] && [[ $RPC_ENABLE -eq 1 ]]; then
-        OPTIONS="$OPTIONS --rpc"
-        if [ ! -z $RPC_API ]; then
-            OPTIONS="$OPTIONS --rpcapi $RPC_API"
-        fi
-        if [ ! -z $RPC_PORT ]; then
-            OPTIONS="$OPTIONS --rpcport $RPC_PORT"
-        fi
-        if [ ! -z $RPC_ADDR ]; then
-            OPTIONS="$OPTIONS --rpcaddr $RPC_ADDR"
-        fi
-        if [ ! -z $RPC_CORSDOMAIN ]; then
-            OPTIONS="$OPTIONS --rpccorsdomain $RPC_CORSDOMAIN"
-        fi
-        if [ ! -z $RPC_VHOSTS ]; then
-            OPTIONS="$OPTIONS --rpcvhosts $RPC_VHOSTS"
-        fi
-    fi
-
-    if [[ ! -z $WS_ENABLE ]] && [[ $WS_ENABLE -eq 1 ]]; then
-        OPTIONS="$OPTIONS --ws"
-        if [ ! -z $WS_API ]; then
-            OPTIONS="$OPTIONS --wsapi $WS_API"
-        fi
-        if [ ! -z $WS_PORT ]; then
-            OPTIONS="$OPTIONS --wsport $WS_PORT"
-        fi
-        if [ ! -z $WS_ADDR ]; then
-            OPTIONS="$OPTIONS --wsaddr $WS_ADDR"
-        fi
-        if [ ! -z $WS_ORIGINS ]; then
-            OPTIONS="$OPTIONS --wsorigins $WS_ORIGINS"
-        fi
-    fi
-
-    # Cypress network => NETWORK_ID is null && NETWORK = "cypress"
-    # Baobab network => NETWORK_ID is null && NETWORK = "baobab"
-    # Else => private network
-    if [[ -z $NETWORK_ID ]]; then
-        if [[ $NETWORK == "baobab" ]]; then
-            OPTIONS="$OPTIONS --baobab"
-        elif [[ $NETWORK == "cypress" ]]; then
-            OPTIONS="$OPTIONS --cypress"
-        else
-            echo
-            echo "[ERROR] network id is not specified and network is not available."
-            echo "Available network: baobab, cypress"
-            exit 1
-        fi
-    else
-        OPTIONS="$OPTIONS --networkid $NETWORK_ID"
-        echo "[INFO] creating a private network: $NETWORK_ID"
-        if [[ ! -z $NETWORK ]]; then
-            echo
-            echo "[WARN] ignoring the specified network: $NETWORK"
-        fi
-    fi
-
-    if [ ! -z $DATA_DIR ]; then
-        OPTIONS="$OPTIONS --datadir $DATA_DIR"
-    fi
-
-    if [ ! -z $PORT ]; then
-        OPTIONS="$OPTIONS --port $PORT"
-    fi
-
-    if [ ! -z $SUBPORT ]; then
-        OPTIONS="$OPTIONS --subport $SUBPORT"
-    fi
-
-    if [ ! -z $SERVER_TYPE ]; then
-        OPTIONS="$OPTIONS --srvtype $SERVER_TYPE"
-    fi
-
-    if [ ! -z $VERBOSITY ]; then
-        OPTIONS="$OPTIONS --verbosity $VERBOSITY"
-    fi
-
-    if [ ! -z $TXPOOL_EXEC_SLOTS_ALL ]; then
-        OPTIONS="$OPTIONS --txpool.exec-slots.all $TXPOOL_EXEC_SLOTS_ALL"
-    fi
-
-    if [ ! -z $TXPOOL_NONEXEC_SLOTS_ALL ]; then
-        OPTIONS="$OPTIONS --txpool.nonexec-slots.all $TXPOOL_NONEXEC_SLOTS_ALL"
-    fi
-
-    if [ ! -z $TXPOOL_EXEC_SLOTS_ACCOUNT ]; then
-        OPTIONS="$OPTIONS --txpool.exec-slots.account $TXPOOL_EXEC_SLOTS_ACCOUNT"
-    fi
-
-    if [ ! -z $TXPOOL_NONEXEC_SLOTS_ACCOUNT ]; then
-        OPTIONS="$OPTIONS --txpool.nonexec-slots.account $TXPOOL_NONEXEC_SLOTS_ACCOUNT"
-    fi
-
-    if [ ! -z $SYNCMODE ]; then
-        OPTIONS="$OPTIONS --syncmode $SYNCMODE"
-    fi
-
-    if [ ! -z $MAXCONNECTIONS ]; then
-        OPTIONS="$OPTIONS --maxconnections $MAXCONNECTIONS"
-    fi
-
-    if [ ! -z $LDBCACHESIZE ]; then
-        OPTIONS="$OPTIONS --db.leveldb.cache-size $LDBCACHESIZE"
-    fi
-
-    if [[ ! -z $NO_DISCOVER ]] && [[ $NO_DISCOVER -eq 1 ]]; then
-        OPTIONS="$OPTIONS --nodiscover"
-    fi
-
-    if [[ ! -z $BOOTNODES ]] && [[ $BOOTNODES != "" ]]; then
-        OPTIONS="$OPTIONS --bootnodes $BOOTNODES"
-    fi
-
-    if [[ ! -z $ADDITIONAL ]] && [[ $ADDITIONAL != "" ]]; then
-        OPTIONS="$OPTIONS $ADDITIONAL"
-    fi
-
-    if [[ ! -z $REWARDBASE ]] && [[ $REWARDBASE != "" ]]; then
-        OPTIONS="$OPTIONS --rewardbase $REWARDBASE"
-    fi
-
-    if [[ ! -z $AUTO_RESTART ]] && [[ $AUTO_RESTART -eq 1 ]]; then
-        OPTIONS="$OPTIONS --autorestart.enable"
-    fi
-
-    BASEDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
-    CURRENTFILE=`basename "$0"`
-    OPTIONS="$OPTIONS --autorestart.daemon.path $BASEDIR/$CURRENTFILE"
-
     $BIN/kcn $OPTIONS >> ${LOG_DIR}/kcnd.out 2>&1 &
     RETVAL=$?
     PIDNUM=$!
-
     set +f
+
     if [ $RETVAL = 0 ]; then
         echo $PIDNUM > ${pidfile}
         echo "Success to start node."
diff --git a/build/rpm/etc/init.d/ksend b/build/rpm/etc/init.d/ksend
--- a/build/rpm/etc/init.d/ksend
+++ b/build/rpm/etc/init.d/ksend
@@ -102,209 +102,211 @@ status_auto_restart_daemon() {
 }
 
 #------------------------Related to Klaytn node functions-----------------------------
+__check_option() {
+    set -f
+    OPTIONS=""
 
-set -f
-OPTIONS=""
+    if [[ ! -z $METRICS ]] && [[ $METRICS -eq 1 ]]; then
+        OPTIONS="$OPTIONS --metrics"
+    fi
 
-if [[ ! -z $METRICS ]] && [[ $METRICS -eq 1 ]]; then
-    OPTIONS="$OPTIONS --metrics"
-fi
+    if [[ ! -z $PROMETHEUS ]] && [[ $PROMETHEUS -eq 1 ]]; then
+        OPTIONS="$OPTIONS --prometheus"
+    fi
 
-if [[ ! -z $PROMETHEUS ]] && [[ $PROMETHEUS -eq 1 ]]; then
-    OPTIONS="$OPTIONS --prometheus"
-fi
+    if [[ ! -z $DB_NO_PARALLEL_WRITE ]] && [[ $DB_NO_PARALLEL_WRITE -eq 1 ]]; then
+        OPTIONS="$OPTIONS --db.no-parallel-write"
+    fi
 
-if [[ ! -z $DB_NO_PARALLEL_WRITE ]] && [[ $DB_NO_PARALLEL_WRITE -eq 1 ]]; then
-    OPTIONS="$OPTIONS --db.no-parallel-write"
-fi
+    if [[ ! -z $MULTICHANNEL ]] && [[ $MULTICHANNEL -eq 1 ]]; then
+        OPTIONS="$OPTIONS --multichannel"
+    fi
 
-if [[ ! -z $MULTICHANNEL ]] && [[ $MULTICHANNEL -eq 1 ]]; then
-    OPTIONS="$OPTIONS --multichannel"
-fi
+    if [[ ! -z $RPC_ENABLE ]] && [[ $RPC_ENABLE -eq 1 ]]; then
+        OPTIONS="$OPTIONS --rpc"
+        if [ ! -z $RPC_API ]; then
+            OPTIONS="$OPTIONS --rpcapi $RPC_API"
+        fi
+        if [ ! -z $RPC_PORT ]; then
+            OPTIONS="$OPTIONS --rpcport $RPC_PORT"
+        fi
+        if [ ! -z $RPC_ADDR ]; then
+            OPTIONS="$OPTIONS --rpcaddr $RPC_ADDR"
+        fi
+        if [ ! -z $RPC_CORSDOMAIN ]; then
+            OPTIONS="$OPTIONS --rpccorsdomain $RPC_CORSDOMAIN"
+        fi
+        if [ ! -z $RPC_VHOSTS ]; then
+            OPTIONS="$OPTIONS --rpcvhosts $RPC_VHOSTS"
+        fi
+    fi
 
-if [[ ! -z $RPC_ENABLE ]] && [[ $RPC_ENABLE -eq 1 ]]; then
-    OPTIONS="$OPTIONS --rpc"
-    if [ ! -z $RPC_API ]; then
-        OPTIONS="$OPTIONS --rpcapi $RPC_API"
+    if [[ ! -z $WS_ENABLE ]] && [[ $WS_ENABLE -eq 1 ]]; then
+        OPTIONS="$OPTIONS --ws"
+        if [ ! -z $WS_API ]; then
+            OPTIONS="$OPTIONS --wsapi $WS_API"
+        fi
+        if [ ! -z $WS_PORT ]; then
+            OPTIONS="$OPTIONS --wsport $WS_PORT"
+        fi
+        if [ ! -z $WS_ADDR ]; then
+            OPTIONS="$OPTIONS --wsaddr $WS_ADDR"
+        fi
+        if [ ! -z $WS_ORIGINS ]; then
+            OPTIONS="$OPTIONS --wsorigins $WS_ORIGINS"
+        fi
     fi
-    if [ ! -z $RPC_PORT ]; then
-        OPTIONS="$OPTIONS --rpcport $RPC_PORT"
-    fi
-    if [ ! -z $RPC_ADDR ]; then
-        OPTIONS="$OPTIONS --rpcaddr $RPC_ADDR"
-    fi
-    if [ ! -z $RPC_CORSDOMAIN ]; then
-        OPTIONS="$OPTIONS --rpccorsdomain $RPC_CORSDOMAIN"
-    fi
-    if [ ! -z $RPC_VHOSTS ]; then
-        OPTIONS="$OPTIONS --rpcvhosts $RPC_VHOSTS"
-    fi
-fi
 
-if [[ ! -z $WS_ENABLE ]] && [[ $WS_ENABLE -eq 1 ]]; then
-    OPTIONS="$OPTIONS --ws"
-    if [ ! -z $WS_API ]; then
-        OPTIONS="$OPTIONS --wsapi $WS_API"
-    fi
-    if [ ! -z $WS_PORT ]; then
-        OPTIONS="$OPTIONS --wsport $WS_PORT"
-    fi
-    if [ ! -z $WS_ADDR ]; then
-        OPTIONS="$OPTIONS --wsaddr $WS_ADDR"
-    fi
-    if [ ! -z $WS_ORIGINS ]; then
-        OPTIONS="$OPTIONS --wsorigins $WS_ORIGINS"
-    fi
-fi
-
-# private network only for Service Chain
-if [[ -z $NETWORK_ID ]]; then
-    echo
-    echo "[ERROR] network id should be specified for Service Chain."
-    exit 1
-else
-    OPTIONS="$OPTIONS --networkid $NETWORK_ID"
-    echo "[INFO] creating a private network: $NETWORK_ID"
-    if [[ ! -z $NETWORK ]]; then
+    # private network only for Service Chain
+    if [[ -z $NETWORK_ID ]]; then
         echo
-        echo "[WARN] ignoring the specified network for Service Chain: $NETWORK"
-    fi
-fi
-
-if [ ! -z $DATA_DIR ]; then
-    OPTIONS="$OPTIONS --datadir $DATA_DIR"
-fi
-
-if [ ! -z $PORT ]; then
-    OPTIONS="$OPTIONS --port $PORT"
-fi
-
-if [ ! -z $SUBPORT ]; then
-    OPTIONS="$OPTIONS --subport $SUBPORT"
-fi
-
-if [ ! -z $SERVER_TYPE ]; then
-    OPTIONS="$OPTIONS --srvtype $SERVER_TYPE"
-fi
-
-if [ ! -z $VERBOSITY ]; then
-    OPTIONS="$OPTIONS --verbosity $VERBOSITY"
-fi
-
-if [ ! -z $TXPOOL_EXEC_SLOTS_ALL ]; then
-    OPTIONS="$OPTIONS --txpool.exec-slots.all $TXPOOL_EXEC_SLOTS_ALL"
-fi
-
-if [ ! -z $TXPOOL_NONEXEC_SLOTS_ALL ]; then
-    OPTIONS="$OPTIONS --txpool.nonexec-slots.all $TXPOOL_NONEXEC_SLOTS_ALL"
-fi
-
-if [ ! -z $TXPOOL_EXEC_SLOTS_ACCOUNT ]; then
-    OPTIONS="$OPTIONS --txpool.exec-slots.account $TXPOOL_EXEC_SLOTS_ACCOUNT"
-fi
-
-if [ ! -z $TXPOOL_NONEXEC_SLOTS_ACCOUNT ]; then
-    OPTIONS="$OPTIONS --txpool.nonexec-slots.account $TXPOOL_NONEXEC_SLOTS_ACCOUNT"
-fi
-
-if [ ! -z TXPOOL_LIFE_TIME ]; then
-    OPTIONS="$OPTIONS --txpool.lifetime $TXPOOL_LIFE_TIME"
-fi
-
-if [ ! -z $SYNCMODE ]; then
-    OPTIONS="$OPTIONS --syncmode $SYNCMODE"
-fi
-
-if [ ! -z $MAXCONNECTIONS ]; then
-    OPTIONS="$OPTIONS --maxconnections $MAXCONNECTIONS"
-fi
-
-if [ ! -z $LDBCACHESIZE ]; then
-    OPTIONS="$OPTIONS --db.leveldb.cache-size $LDBCACHESIZE"
-fi
-
-if [[ ! -z $NO_DISCOVER ]] && [[ $NO_DISCOVER -eq 1 ]]; then
-    OPTIONS="$OPTIONS --nodiscover"
-fi
-
-if [[ ! -z $BOOTNODES ]] && [[ $BOOTNODES != "" ]]; then
-    OPTIONS="$OPTIONS --bootnodes $BOOTNODES"
-fi
-
-if [[ ! -z $SC_MAIN_BRIDGE ]] && [[ $SC_MAIN_BRIDGE -eq 1 ]]; then
-    OPTIONS="$OPTIONS --mainbridge --mainbridgeport $SC_MAIN_BRIDGE_PORT"
-    if [[ ! -z $SC_MAIN_BRIDGE_INDEXING ]] && [[ $SC_MAIN_BRIDGE_INDEXING -eq 1 ]]; then
-        OPTIONS="$OPTIONS --childchainindexing"
-    fi
-fi
-
-if [[ ! -z $SC_SUB_BRIDGE ]] && [[ $SC_SUB_BRIDGE -eq 1 ]]; then
-    OPTIONS="$OPTIONS --subbridge --subbridgeport $SC_SUB_BRIDGE_PORT --chaintxperiod $SC_ANCHORING_PERIOD --chaintxlimit $SC_TX_LIMIT "
-    OPTIONS="$OPTIONS --parentchainid $SC_PARENT_CHAIN_ID"
-    if [[ ! -z $SC_ANCHORING ]] && [[ $SC_ANCHORING -eq 1 ]]; then
-            OPTIONS="$OPTIONS --anchoring"
+        echo "[ERROR] network id should be specified for Service Chain."
+        exit 1
+    else
+        OPTIONS="$OPTIONS --networkid $NETWORK_ID"
+        echo "[INFO] creating a private network: $NETWORK_ID"
+        if [[ ! -z $NETWORK ]]; then
+            echo
+            echo "[WARN] ignoring the specified network for Service Chain: $NETWORK"
+        fi
     fi
 
-    if [[ ! -z $SC_KAS_ANCHOR ]] && [[ $SC_KAS_ANCHOR -eq 1 ]]; then
-        OPTIONS="$OPTIONS --kas.sc.anchor"
-
-        if [[ ! -z $SC_KAS_ANCHOR_PERIOD ]]; then
-            OPTIONS="$OPTIONS --kas.sc.anchor.period $SC_KAS_ANCHOR_PERIOD"
-        fi
-
-        if [[ -z $SC_KAS_ANCHOR_URL ]]; then
-            echo
-            echo "[ERROR] kas.sc.anchor.url should be specified for KAS Anchor."
-            exit 1
-        fi
-        OPTIONS="$OPTIONS --kas.sc.anchor.url $SC_KAS_ANCHOR_URL"
-
-        if [[ -z $SC_KAS_ANCHOR_OPERATOR ]]; then
-            echo
-            echo "[ERROR] kas.sc.anchor.operator should be specified for KAS Anchor."
-            exit 1
-        fi
-        OPTIONS="$OPTIONS --kas.sc.anchor.operator $SC_KAS_ANCHOR_OPERATOR"
-
-        if [[ -z $SC_KAS_ANCHOR_ACCESS_KEY ]]; then
-            echo
-            echo "[ERROR] kas.accesskey should be specified for KAS Anchor."
-            exit 1
-        fi
-        OPTIONS="$OPTIONS --kas.accesskey $SC_KAS_ANCHOR_ACCESS_KEY"
-
-        if [[ -z $SC_KAS_ANCHOR_SECRET_KEY ]]; then
-            echo
-            echo "[ERROR] kas.secretkey should be specified for KAS Anchor."
-            exit 1
-        fi
-        OPTIONS="$OPTIONS --kas.secretkey $SC_KAS_ANCHOR_SECRET_KEY"
-
-        if [[ -z $SC_KAS_ANCHOR_X_CHAIN_ID ]]; then
-            echo
-            echo "[ERROR] kas.x-chain-id should be specified for KAS Anchor."
-            exit 1
-        fi
-        OPTIONS="$OPTIONS --kas.x-chain-id $SC_KAS_ANCHOR_X_CHAIN_ID"
+    if [ ! -z $DATA_DIR ]; then
+        OPTIONS="$OPTIONS --datadir $DATA_DIR"
     fi
-fi
 
-if [[ ! -z $VTRECOVERY ]] && [[ $VTRECOVERY -eq 1 ]]; then
-    OPTIONS="$OPTIONS --vtrecovery"
-fi
+    if [ ! -z $PORT ]; then
+        OPTIONS="$OPTIONS --port $PORT"
+    fi
 
-if [[ ! -z $ADDITIONAL ]] && [[ $ADDITIONAL != "" ]]; then
-    OPTIONS="$OPTIONS $ADDITIONAL"
-fi
+    if [ ! -z $SUBPORT ]; then
+        OPTIONS="$OPTIONS --subport $SUBPORT"
+    fi
 
-if [[ ! -z $AUTO_RESTART ]] && [[ $AUTO_RESTART -eq 1 ]]; then
-    OPTIONS="$OPTIONS --autorestart.enable"
-fi
+    if [ ! -z $SERVER_TYPE ]; then
+        OPTIONS="$OPTIONS --srvtype $SERVER_TYPE"
+    fi
 
-BASEDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
-CURRENTFILE=`basename "$0"`
-OPTIONS="$OPTIONS --autorestart.daemon.path $BASEDIR/$CURRENTFILE"
-set +f
+    if [ ! -z $VERBOSITY ]; then
+        OPTIONS="$OPTIONS --verbosity $VERBOSITY"
+    fi
+
+    if [ ! -z $TXPOOL_EXEC_SLOTS_ALL ]; then
+        OPTIONS="$OPTIONS --txpool.exec-slots.all $TXPOOL_EXEC_SLOTS_ALL"
+    fi
+
+    if [ ! -z $TXPOOL_NONEXEC_SLOTS_ALL ]; then
+        OPTIONS="$OPTIONS --txpool.nonexec-slots.all $TXPOOL_NONEXEC_SLOTS_ALL"
+    fi
+
+    if [ ! -z $TXPOOL_EXEC_SLOTS_ACCOUNT ]; then
+        OPTIONS="$OPTIONS --txpool.exec-slots.account $TXPOOL_EXEC_SLOTS_ACCOUNT"
+    fi
+
+    if [ ! -z $TXPOOL_NONEXEC_SLOTS_ACCOUNT ]; then
+        OPTIONS="$OPTIONS --txpool.nonexec-slots.account $TXPOOL_NONEXEC_SLOTS_ACCOUNT"
+    fi
+
+    if [ ! -z TXPOOL_LIFE_TIME ]; then
+        OPTIONS="$OPTIONS --txpool.lifetime $TXPOOL_LIFE_TIME"
+    fi
+
+    if [ ! -z $SYNCMODE ]; then
+        OPTIONS="$OPTIONS --syncmode $SYNCMODE"
+    fi
+
+    if [ ! -z $MAXCONNECTIONS ]; then
+        OPTIONS="$OPTIONS --maxconnections $MAXCONNECTIONS"
+    fi
+
+    if [ ! -z $LDBCACHESIZE ]; then
+        OPTIONS="$OPTIONS --db.leveldb.cache-size $LDBCACHESIZE"
+    fi
+
+    if [[ ! -z $NO_DISCOVER ]] && [[ $NO_DISCOVER -eq 1 ]]; then
+        OPTIONS="$OPTIONS --nodiscover"
+    fi
+
+    if [[ ! -z $BOOTNODES ]] && [[ $BOOTNODES != "" ]]; then
+        OPTIONS="$OPTIONS --bootnodes $BOOTNODES"
+    fi
+
+    if [[ ! -z $SC_MAIN_BRIDGE ]] && [[ $SC_MAIN_BRIDGE -eq 1 ]]; then
+        OPTIONS="$OPTIONS --mainbridge --mainbridgeport $SC_MAIN_BRIDGE_PORT"
+        if [[ ! -z $SC_MAIN_BRIDGE_INDEXING ]] && [[ $SC_MAIN_BRIDGE_INDEXING -eq 1 ]]; then
+            OPTIONS="$OPTIONS --childchainindexing"
+        fi
+    fi
+
+    if [[ ! -z $SC_SUB_BRIDGE ]] && [[ $SC_SUB_BRIDGE -eq 1 ]]; then
+        OPTIONS="$OPTIONS --subbridge --subbridgeport $SC_SUB_BRIDGE_PORT --chaintxperiod $SC_ANCHORING_PERIOD --chaintxlimit $SC_TX_LIMIT "
+        OPTIONS="$OPTIONS --parentchainid $SC_PARENT_CHAIN_ID"
+        if [[ ! -z $SC_ANCHORING ]] && [[ $SC_ANCHORING -eq 1 ]]; then
+                OPTIONS="$OPTIONS --anchoring"
+        fi
+
+        if [[ ! -z $SC_KAS_ANCHOR ]] && [[ $SC_KAS_ANCHOR -eq 1 ]]; then
+            OPTIONS="$OPTIONS --kas.sc.anchor"
+
+            if [[ ! -z $SC_KAS_ANCHOR_PERIOD ]]; then
+                OPTIONS="$OPTIONS --kas.sc.anchor.period $SC_KAS_ANCHOR_PERIOD"
+            fi
+
+            if [[ -z $SC_KAS_ANCHOR_URL ]]; then
+                echo
+                echo "[ERROR] kas.sc.anchor.url should be specified for KAS Anchor."
+                exit 1
+            fi
+            OPTIONS="$OPTIONS --kas.sc.anchor.url $SC_KAS_ANCHOR_URL"
+
+            if [[ -z $SC_KAS_ANCHOR_OPERATOR ]]; then
+                echo
+                echo "[ERROR] kas.sc.anchor.operator should be specified for KAS Anchor."
+                exit 1
+            fi
+            OPTIONS="$OPTIONS --kas.sc.anchor.operator $SC_KAS_ANCHOR_OPERATOR"
+
+            if [[ -z $SC_KAS_ANCHOR_ACCESS_KEY ]]; then
+                echo
+                echo "[ERROR] kas.accesskey should be specified for KAS Anchor."
+                exit 1
+            fi
+            OPTIONS="$OPTIONS --kas.accesskey $SC_KAS_ANCHOR_ACCESS_KEY"
+
+            if [[ -z $SC_KAS_ANCHOR_SECRET_KEY ]]; then
+                echo
+                echo "[ERROR] kas.secretkey should be specified for KAS Anchor."
+                exit 1
+            fi
+            OPTIONS="$OPTIONS --kas.secretkey $SC_KAS_ANCHOR_SECRET_KEY"
+
+            if [[ -z $SC_KAS_ANCHOR_X_CHAIN_ID ]]; then
+                echo
+                echo "[ERROR] kas.x-chain-id should be specified for KAS Anchor."
+                exit 1
+            fi
+            OPTIONS="$OPTIONS --kas.x-chain-id $SC_KAS_ANCHOR_X_CHAIN_ID"
+        fi
+    fi
+
+    if [[ ! -z $VTRECOVERY ]] && [[ $VTRECOVERY -eq 1 ]]; then
+        OPTIONS="$OPTIONS --vtrecovery"
+    fi
+
+    if [[ ! -z $ADDITIONAL ]] && [[ $ADDITIONAL != "" ]]; then
+        OPTIONS="$OPTIONS $ADDITIONAL"
+    fi
+
+    if [[ ! -z $AUTO_RESTART ]] && [[ $AUTO_RESTART -eq 1 ]]; then
+        OPTIONS="$OPTIONS --autorestart.enable"
+    fi
+
+    BASEDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
+    CURRENTFILE=`basename "$0"`
+    OPTIONS="$OPTIONS --autorestart.daemon.path $BASEDIR/$CURRENTFILE"
+    set +f
+}
+
 
 start_node() {
         echo -n "Starting $prog: "
@@ -314,6 +316,8 @@ start_node() {
 
         __pids_var_run "$prog" "$pidfile"
         [ -n "$pid" ] && echo && return
+
+        __check_option
 
         set -f
         $ksen $OPTIONS >> ${LOG_DIR}/ksend.out 2>&1 &
